from qiskit import *
Adder = QuantumCircuit(5)
Adder.mct([0,1,2,3],4)
Adder.mct([0,1,2],3)
Adder.ccx(0,1,2)
Adder.cx(0,1)
A = Adder.to_gate()
type(A)
AddBlocker = QuantumCircuit(6)
AddBlocker.mct([0,1,2,3,4],5)
AddBlocker.cx(5,1)
AB = AddBlocker.to_gate() 
type(AB)
DecreaserBlocker = QuantumCircuit(6)
DecreaserBlocker.x(1)
DecreaserBlocker.x(2)
DecreaserBlocker.x(3)
DecreaserBlocker.x(4)
DecreaserBlocker.mct([0,2,3,4],5)
DecreaserBlocker.x(1)
DecreaserBlocker.x(2)
DecreaserBlocker.x(3)
DecreaserBlocker.x(4)
DecreaserBlocker.cx(5,1)
DecreaserBlocker.cx(5,2)
DB = DecreaserBlocker.to_gate()
type(DB)
Decreaser = QuantumCircuit(5)
Decreaser.cx(0,1)
Decreaser.ccx(0,1,2)
Decreaser.mct([0,1,2],3)
Decreaser.mct([0,1,2,3],4)
D = Decreaser.to_gate()
type(D)



q = QuantumRegister(6)
c = ClassicalRegister(4)
qc = QuantumCircuit(q, c)
qc.rx(pi/2,q[0])
qc.x(4)
for i in range(10):
    qc.rx(pi/2,q[0])
    qc.h(0)
    qc.append(AB,[0,1,2,3,4,5])
    qc.reset(5)
    qc.append(A,[0,1,2,3,4])
    qc.x(0)
    qc.append(DB,[0,1,2,3,4,5])
    qc.reset(5)
    qc.append(D,[0,1,2,3,4])
    qc.reset(q[0])
qc.measure(q[1],c[0])
qc.measure(q[2],c[1])
qc.measure(q[3],c[2])
qc.measure(q[4],c[3])
qc.draw('mpl')




from qiskit.visualization import plot_histogram
%matplotlib inline
backend = BasicAer.get_backend('qasm_simulator')
job = execute(qc, backend)
plot_histogram(job.result().get_counts(), color='midnightblue', title="Random Walk for 4 qibits")
