from qiskit import *
Hubert = QuantumCircuit(4)
Hubert.mct([0,1,2],3)
Hubert.ccx(0,1,2)
Hubert.cx(0,1) 
p1 = Hubert.to_gate()
type(p1)
PCR = QuantumCircuit(4)
PCR.mct([0,1,2],3)
PCR.ccx(0,1,2)
PCR.cx(0,1) 
p2 = PCR.to_gate()
q = QuantumRegister(4)
c = ClassicalRegister(2)
qc = QuantumCircuit(q, c)
qc.h(0)
qc.append(p1, [0,1,2,3])
qc.x(0)
qc.append(p2, [0,1,2,3])
qc.draw('mpl')
